spring.application.name=azarcafetero
server.port=8089

# Logging
logging.level.com.aguardientes.azarcafetero=DEBUG
logging.level.org.springframework.messaging=DEBUG

# Wallet service
wallet.service.url=${WALLET_SERVICE_URL:http://127.0.0.1:8095}
internal.api.key=${INTERNAL_API_KEY}